sudo: false
language: ruby
rvm:
  - 2.4.1
before_install: gem install bundler -v 1.16.1

# CodeClimate Test Reporter
env:
  global:
    - CC_TEST_REPORTER_ID=21adedfd934b53e16aeaef7d569a3396c5f80082fb605612665b9478996044aa
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
